### PR TITLE
Add support for unordered values in lists

### PR DESCRIPTION
**Pull request by andreagrandi**

### CODE REVIEW

**Comment by jakul** [comment]
How is this different to https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertDictEqual?

**Comment by andreagrandi** [comment]
@jakul it's called dict-utils but you also have other features like:
- searching for a specific key/value inside a dict, regardless of the dict structure
- comparing two different dicts for specific keys
- handling unordered items

**Comment by jakul** [comment]
@andreagrandi Why do you need to add the functionality contained within this PR? How is the functionality provided by Python insufficient?

**Comment by andreagrandi** [comment]
Hi @jakul I explained in the three points above why we introduced this library a while ago. It was already used in Facebook tests but it had a problem related to the fact that was considering a list of the same elements in a different order like two different lists, so I fixed it.

**Pull request merged**
